/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#271900",
        "on-primary-fixed": "#390c00",
        "inverse-primary": "#ab3600",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#303034",
        "on-primary-fixed-variant": "#832700",
        "on-background": "#e4e1e7",
        "on-error": "#690005",
        "secondary-fixed-dim": "#ffba27",
        error: "#ffb4ab",
        "secondary-container": "#fbb400",
        "on-secondary-fixed-variant": "#5e4100",
        "surface-container-low": "#1b1b1f",
        "error-container": "#93000a",
        "surface-variant": "#353439",
        "outline-variant": "#5c4037",
        "surface-container-highest": "#353439",
        "surface-container-high": "#2a292e",
        "primary-fixed": "#ffdbcf",
        "tertiary-container": "#00a572",
        tertiary: "#4edea3",
        "inverse-surface": "#e4e1e7",
        "surface-dim": "#131317",
        background: "#131317",
        "on-surface": "#e4e1e7",
        surface: "#131317",
        "surface-bright": "#39393d",
        "surface-container-lowest": "#0e0e12",
        "on-tertiary": "#003824",
        primary: "#ffb59c",
        outline: "#ac897e",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-container": "#00311f",
        "secondary-fixed": "#ffdea9",
        "tertiary-fixed-dim": "#4edea3",
        "surface-tint": "#ffb59c",
        "surface-container": "#1f1f23",
        "primary-fixed-dim": "#ffb59c",
        "on-secondary-container": "#694900",
        "tertiary-fixed": "#6ffbbe",
        "on-primary": "#5c1900",
        "on-surface-variant": "#e5beb2",
        "on-primary-container": "#511500",
        "primary-container": "#ff570b",
        "on-secondary": "#422c00",
        "on-tertiary-fixed-variant": "#005236",
        secondary: "#ffd795",
      },
      spacing: {
        "space-xl": "2rem",
        gutter: "1rem",
        "space-md": "1rem",
        "space-3xl": "4rem",
        "space-xs": "0.5rem",
        "space-2xs": "0.25rem",
        "space-2xl": "3rem",
        "space-lg": "1.5rem",
        "space-sm": "0.75rem",
        "edge-margin-tablet": "2rem",
        "edge-margin-mobile": "1.25rem",
      },
      fontFamily: {
        "display-hero": ["Syne", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Syne", "sans-serif"],
        "title-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Syne", "sans-serif"],
        "headline-lg": ["Syne", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "60px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-sm": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["38px", { lineHeight: "42px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
